# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="is_key1",
            field=models.BooleanField(null=True),
        ),
    ]
