# -*- coding: utf-8 -*-
# Generated by Django 4.1.7 on 2023-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_report_buy_sell_hold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-last_modified"]},
        ),
        migrations.AddField(
            model_name="report",
            name="report_name",
            field=models.CharField(default="Default Report Name", max_length=100),
            preserve_default=False,
        ),
    ]
