# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-02-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_report_corpus_flag_report_in_idf_flag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="plaintext",
            field=models.TextField(default=None, null=True),
        ),
    ]
