# -*- coding: utf-8 -*-
# Generated by Django 4.1.7 on 2023-02-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_sentence"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermIDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.TextField()),
                ("term_frequency", models.IntegerField(default=0)),
                ("idf", models.FloatField(default=0.0)),
            ],
        ),
    ]
