# -*- coding: utf-8 -*-
# Generated by Django 4.1.7 on 2023-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_report_corpus_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="profile_pictures/%Y/%m"
            ),
        ),
    ]
