version: '3.8'
volumes:
  postgresData:
services:
  backend:
    image: registry.hub.docker.com/willholbrook/analyst_report_summarizer_combined_populated:latest
    container_name: AnalystReportSummarizerCombined
    environment:
      DJANGO_DATABASE_TYPE: postgres
      GROBID_SERVER_HOSTNAME: grobid
    ports:
      - 8030:80
    restart: on-failure
    depends_on:
      - db
      - grobid
  db:
    image: registry.hub.docker.com/willholbrook/analyst_report_summarizer_database_populated:latest
    container_name: AnalystReportSummarizerDatabase
    environment:
      POSTGRES_PASSWORD: postgres
    restart: on-failure
  grobid:
    image: registry.hub.docker.com/grobid/grobid:0.7.2
    container_name: AnalystReportSummarizerGrobid
    restart: on-failure
