# Verion of docker-compose to use
version: "3.8"

services:
  backend:
    image: analyst_report_summarizer_dev

    environment:
      GROBID_SERVER_HOSTNAME: grobid

    # Maps port on the local machine to port on Docker image
    ports:
      - "8000:8000"

    volumes:
    # Copy changes made to the project to your image in real-time.
      - .\backend:/opt/app
    depends_on:
      - grobid

  grobid:
    image: registry.hub.docker.com/grobid/grobid:0.7.2
    domainname: "grobidwillholbrook"
    ports:
      - "8020:8070"
