# Generated by Django 4.1.3 on 2022-11-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_charachter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charachter',
            new_name='Character',
        ),
    ]
