name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  push-to-github:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/WillHolbrook/FYPCodeRepo.git
      - run: ls -l
      - run: pwd
