name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  push-to-github:
    runs-on: ubuntu-latest
    steps:    
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{secrets.LOCAL_FYP_CODE_REPO_KEY}}
      - run: git clone git@github.com:WillHolbrook/FYPCodeRepo.git
      - run: cd ./FYPCodeRepo
      - run: git checkout -B "develop"
      - run: ls -l
      
