name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
#   push:
#     branches: [ develop ]
#   pull_request:
#     branches: [ develop ]
jobs:
  push-to-github:
    runs-on: ubuntu-latest
    steps:             
      - uses: MrSquaare/ssh-setup-action@v2
        with:
          host: github.com
          private-key: ${{ secrets.LOCAL_FYP_CODE_REPO_KEY }}
      - run: git clone git@github.com:WillHolbrook/FYPCodeRepo.git . -o github
#       - run: git clone git@git.cs.bham.ac.uk:projects-2022-23/wdh961.git .
      - uses: MrSquaare/ssh-setup-action@v2
        with:
          host: git.cs.bham.ac.uk
          private-key: ${{ secrets.GITLAB_FYP_CODE_REPO_KEY }} 
      - run: git remote add gitlab git@git.cs.bham.ac.uk:projects-2022-23/wdh961.git
      - run: git remote -v
      - run: |
          git fetch gitlab
          git status
          tree
      - run: git log
      - run: git log gitlab/develop
#       - run: git pull gitlab develop
      - run: git push gitlab develop
      
