name: push-from-github-to-gitlab
run-name: push-from-github-to-gitlab
on:
  push:
    branches: [ develop ]
jobs:
  push-to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: MrSquaare/ssh-setup-action@v2
        with:
          host: github.com
          private-key: ${{ secrets.LOCAL_FYP_CODE_REPO_KEY }}
      - run: git clone git@github.com:WillHolbrook/FYPCodeRepo.git . -o github
      - uses: MrSquaare/ssh-setup-action@v2
        with:
          host: git.cs.bham.ac.uk
          private-key: ${{ secrets.GITLAB_FYP_CODE_REPO_KEY }}
      - run: git remote add gitlab git@git.cs.bham.ac.uk:projects-2022-23/wdh961.git
      - run: git push gitlab develop
