name: python-workflow
run-name: python-workflow
on:
  push:
    branches: [ develop, 4-set-up-build-and-test-cicd-pipeline-for-python ]
  pull_request:
    branches: [ develop, 4-set-up-build-and-test-cicd-pipeline-for-python ]
jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        mkdir artifacts
        
    - name: Lint with PyLint
      run: |
        pylint $(git ls-files -- '*.py' ':!:*/migrations/*' ':!:*/migrations/*' ':!:manage.py') --load-plugins=pylint_django --django-settings-module=analyst_report_summarizer.settings --disable=wrong-import-order 2>&1 | tee artifacts/lint_out.txt
    - name: Upload Lint Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint_out
        path: backend/artifacts/lint_out.txt
    
    - name: Run Unit Tests
      run: |
        python -m coverage run manage.py test 2>&1 | tee artifacts/unit_tests_out.txt
        coverage report
        coverage xml -o ./artifacts/coverage_report.xml
    - name: Upload Test Artifact
      uses: actions/upload-artifact@v3
      with:
        name: unit_test_out
        path: backend/artifacts/unit_tests_out.txt
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage_report
        path: backend/artifacts/coverage_report.xml        
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: backend/artifacts/coverage_report.xml
        badge: true
        format: markdown
        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md    
    
    - name: Run Django Security Tests
      run: |
        python manage.py check --deploy --fail-level ERROR
