name: python-workflow
run-name: python-workflow
on:
  push:
    branches: [ develop, 4-set-up-build-and-test-cicd-pipeline-for-python ]
  pull_request:
    branches: [ develop, 4-set-up-build-and-test-cicd-pipeline-for-python ]
jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Lint with PyLint
      run: |
        pylint $(git ls-files '*.py' --exclude="**/migrations/**") --load-plugins=pylint_django --django-settings-module=analyst_report_summarizer.settings --disable=wrong-import-order
